server:
  port: 9443
#  ssl:
#    key-store: file:///E://mykeys.jks
#    key-password: marco520
#    trust-store-password: marco520

spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: marco520
    driverClassName: com.mysql.jdbc.Driver
    connectionProperties: druid.stat.mergeSql=true
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:template/
    suffix: .html
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
    mode: HTML5
  mvc:
    static-path-pattern: classpath:static/**




mybatis:
  #实体类所在包
  type-aliases-package: com.marco.dao.entity
  mapperLocations: classpath:mapper/*.xml
management:
  endpoint:
    env:
      enabled: true
    beans:
      enabled: true


---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaosha?autoReconnect=true&characterEncoding=utf8&useSSL=false

---
# 测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaosha?autoReconnect=true&characterEncoding=utf8&useSSL=false

---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaosha?autoReconnect=true&characterEncoding=utf8&useSSL=false