server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: marco520
    driverClassName: com.mysql.jdbc.Driver
    connectionProperties: druid.stat.mergeSql=true
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:template/
    suffix: .html
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
    mode: HTML5
  mvc:
    static-path-pattern: classpath:static/**



mybatis:
  #实体类所在包
  type-aliases-package: com.marco.dao.entity
  mapperLocations: classpath:mapper/*.xml

---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.175.129/miaosha?autoReconnect=true&characterEncoding=utf8&useSSL=false

---
# 测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.175.129/miaosha?autoReconnect=true&characterEncoding=utf8&useSSL=false

---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.175.129/miaosha?autoReconnect=true&characterEncoding=utf8&useSSL=false